<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckoutBtn</name>
   <tag></tag>
   <elementGuidId>0d71c51c-dea0-4909-87d4-7f6d131d64d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkout&quot;]</value>
      <webElementGuid>bbb83c00-ae20-427c-a5ce-26239c186d29</webElementGuid>
   </webElementProperties>
</WebElementEntity>
