<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContinueBtn</name>
   <tag></tag>
   <elementGuidId>9ba388c5-ca4f-4515-8f04-ae7de96c164e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='continue']</value>
      <webElementGuid>cd764272-a0fa-439d-8010-f8b3c5bb226a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
