<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FinishBtn</name>
   <tag></tag>
   <elementGuidId>33664063-e7e2-4052-aec8-3ab372e434fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='finish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='finish']</value>
      <webElementGuid>e5b447bb-c173-455f-87a0-f5d9a6a0207d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
