<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstNameField</name>
   <tag></tag>
   <elementGuidId>cf99d4d4-a49f-46ff-8f12-dfe8de15d5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='first-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='first-name']</value>
      <webElementGuid>5913d0d1-6830-45cb-9552-d3cf297f1e53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
