<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastNameField</name>
   <tag></tag>
   <elementGuidId>1addeca2-86f7-40e9-899b-2c50362bdd7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='last-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='last-name']</value>
      <webElementGuid>9b34851f-07c6-480e-ad0c-f618f2000fbc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
