<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PasswordField</name>
   <tag></tag>
   <elementGuidId>123dc3b4-9f31-4aa6-83a1-b36c4ecc4edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;password&quot;]</value>
      <webElementGuid>69539441-6d58-4fb6-a2cf-17f91de1fda7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
