<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductsText</name>
   <tag></tag>
   <elementGuidId>7fbf625b-d7ac-44d3-b693-cebf9321bece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='title']</value>
      <webElementGuid>46890f7e-28f7-435e-a434-2d6d239f7bab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
