<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductPrices</name>
   <tag></tag>
   <elementGuidId>16ca8efd-14ef-439f-8711-5e621d51f1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='inventory_item_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='inventory_item_price']</value>
      <webElementGuid>a8f306c3-3d86-4439-9f01-b7814beef94c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
